name: Build and Upload

on:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-dist:
    name: Build and Upload
    uses: ./.github/workflows/verify-build.yml
    with:
      release: true
      runner-archs: '["amd64", "arm64"]'
      package: 'virtio-accel'
      options: ''
      upload-subpath: 'virtio-accel'
    secrets: inherit
